version: '3.2'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - nginx:/etc/nginx
  docker-gen:
    image: docker-gen
    container_name: docker-gen
    volumes:
      - nginx:/root/nginx/
